mindmap
LLM((Large Language Models: Generative Pre-trained Transformers. Generates text based on input text.))
    Chat bots: converses with a user and provides the conversation to the LLM to generate a response. As the conversation progresses, the input also accordingly grows to provide more context to the LLM.
    RAG: Retrieval Augmented Generation. Takes user Input and Retrieves a set of documents most relevant to the Input. These Retrieved documents are used to Augment the original Input and is sent to the LLM to Generate an output.